from .Bolson import Bolson as BolsonResource
from .Bolson import Bolsones as BolsonesResource
from .BolsonVenta import BolsonVenta as BolsonVentaResource
from .BolsonVenta import BolsonesVentas as BolsonesVentasResource
from .BolsonPendiente import BolsonPendiente as BolsonPendienteResource
from .BolsonPendiente import BolsonesPendientes as BolsonesPendientesResource
from .BolsonPrevio import BolsonPrevio as BolsonPrevioResource
from .BolsonPrevio import BolsonesPrevios as BolsonesPreviosResource
from .Producto import Producto as ProductoResource
from .Producto import Productos as ProductosResource
from .Compra import Compra as CompraResource
from .Compra import Compras as ComprasResource
from .Cliente import Cliente as ClienteResource
from .Cliente import Clientes as ClientesResource
from .Proveedor import Proveedor as ProveedorResource
from .Proveedor import Proveedores as ProveedoresResource
from .Admin import Admin as AdminResource
